apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
data:
  DB_HOST: mysql
  DB_DATABASE: laravel
  DB_USERNAME: laravel
  DB_PORT: "3306"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  CACHE_DRIVER: "redis"
  SESSION_DRIVER: "redis"
  QUEUE_CONNECTION: "redis"