apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-storage
  labels:
    app: laravel
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-cache
  labels:
    app: laravel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard